<?php
// includes/blog-data.php — single source of truth for all blog post metadata.
// Newest post FIRST. Every consumer (blog index, homepage preview, related
// articles, sitemap.php) reads this array. Never hardcode post lists elsewhere.

$blogPosts = [
    [
        'slug'     => 'towing-richmond-tx-complete-guide',
        'title'    => 'Towing in Richmond, TX: The Complete 2026 Guide',
        'excerpt'  => 'How towing actually works in Richmond and Fort Bend County — real response times, what dispatch needs from you, how pricing is set, and what to expect from the moment you call to the moment your car is dropped off.',
        'image'    => 'https://db.pageone.cloud/storage/v1/object/public/client-assets/twin-cities-towing-inc/photos/1776710964435-vw221x-o__26_.jpg',
        'alt'      => 'Twin Cities Towing INC tow truck loading a vehicle in Richmond, TX — complete local towing guide for Fort Bend County drivers',
        'date'     => 'July 18, 2026',
        'dateISO'  => '2026-07-18',
        'category' => 'Towing Guides',
        'readtime' => '9 min read',
    ],
    [
        'slug'     => 'towing-cost-richmond-tx',
        'title'    => 'How Much Does Towing Cost in Richmond, TX?',
        'excerpt'  => 'Most local tows in Richmond run $75–$125, but distance, vehicle type, and time of day all move the number. Here is a straight breakdown of hook-up fees, per-mile rates, and what a fair quote looks like in Fort Bend County.',
        'image'    => 'https://db.pageone.cloud/storage/v1/object/public/client-assets/twin-cities-towing-inc/photos/1776710965325-3pq2z7-o__25_.jpg',
        'alt'      => 'Tow truck operator securing a car for transport in Richmond, TX — breakdown of local towing costs and per-mile rates',
        'date'     => 'July 5, 2026',
        'dateISO'  => '2026-07-05',
        'category' => 'Towing Guides',
        'readtime' => '7 min read',
    ],
    [
        'slug'     => 'what-to-do-after-car-accident',
        'title'    => 'What to Do After a Car Accident in Fort Bend County',
        'excerpt'  => 'The minutes after a collision on US-59 or SH-99 are disorienting. This step-by-step covers moving to safety, calling 911, documenting the scene, and getting your vehicle towed without signing anything you shouldn\'t.',
        'image'    => 'https://db.pageone.cloud/storage/v1/object/public/client-assets/twin-cities-towing-inc/photos/1776710966205-obsbo8-o__24_.jpg',
        'alt'      => 'Accident recovery tow truck at a collision scene in Fort Bend County, TX — steps to take after a car accident near Richmond',
        'date'     => 'June 20, 2026',
        'dateISO'  => '2026-06-20',
        'category' => 'Roadside Help',
        'readtime' => '8 min read',
    ],
    [
        'slug'     => 'flatbed-vs-wheel-lift-towing',
        'title'    => 'Flatbed vs. Wheel-Lift Towing: Which Does Your Car Need?',
        'excerpt'  => 'AWD drivetrains, lowered suspensions, and luxury cars usually need a flatbed — but a wheel-lift is faster and cheaper for many short local tows. Here is how to know which method your vehicle actually requires.',
        'image'    => 'https://db.pageone.cloud/storage/v1/object/public/client-assets/twin-cities-towing-inc/photos/1776710967025-6x3qzu-o__23_.jpg',
        'alt'      => 'Flatbed tow truck carrying a car near Richmond, TX — comparing flatbed and wheel-lift towing methods',
        'date'     => 'June 8, 2026',
        'dateISO'  => '2026-06-08',
        'category' => 'Towing Guides',
        'readtime' => '6 min read',
    ],
    [
        'slug'     => 'car-wont-start-common-causes',
        'title'    => 'Car Won\'t Start? 7 Common Causes and What to Do Next',
        'excerpt'  => 'Dead battery, failed starter, bad alternator, empty tank — most no-start situations trace back to seven causes. Learn how to tell them apart in your driveway, and which ones a Richmond roadside call can fix on the spot.',
        'image'    => 'https://db.pageone.cloud/storage/v1/object/public/client-assets/twin-cities-towing-inc/photos/1776710967925-y6udug-o__22_.jpg',
        'alt'      => 'Roadside assistance technician jump-starting a car that won\'t start in Richmond, TX — diagnosing common no-start causes',
        'date'     => 'May 22, 2026',
        'dateISO'  => '2026-05-22',
        'category' => 'Roadside Help',
        'readtime' => '7 min read',
    ],
    [
        'slug'     => 'texas-towing-laws-your-rights',
        'title'    => 'Texas Towing Laws: Your Rights When Your Car Gets Towed',
        'excerpt'  => 'Texas caps private-property tow fees, requires signage, and gives you the right to a tow hearing for as little as $20. Know what a towing company in Fort Bend County can and cannot legally do with your vehicle.',
        'image'    => 'https://db.pageone.cloud/storage/v1/object/public/client-assets/twin-cities-towing-inc/photos/1776710968765-9pnrt6-o__21_.jpg',
        'alt'      => 'Tow truck removing a vehicle from a private lot in Richmond, TX — driver rights under Texas towing law',
        'date'     => 'May 9, 2026',
        'dateISO'  => '2026-05-09',
        'category' => 'Towing Guides',
        'readtime' => '8 min read',
    ],
];
